# Generated by Django 4.0.2 on 2022-05-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='text',
            field=models.TextField(default='', max_length=250),
        ),
    ]
