# Generated by Django 4.0.2 on 2022-05-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_report_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='text',
            field=models.CharField(default='', max_length=250),
        ),
    ]
