# Generated by Django 4.0.2 on 2022-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_id',
            field=models.IntegerField(default='6'),
        ),
    ]
