# Generated by Django 4.0.2 on 2022-05-29 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('report', '0004_report_reported_body_report_reported_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reported_id',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reported_body', 'reported_id'], name='report_repo_reporte_48fee4_idx'),
        ),
    ]
