# Generated by Django 4.0.2 on 2022-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_alter_report_reported_body_alter_report_reported_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_id',
            field=models.PositiveIntegerField(),
        ),
    ]
