# Generated by Django 4.0.2 on 2022-02-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comments_blogpost_public_commentadmin_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(),
        ),
    ]
