# Generated by Django 4.0.2 on 2022-03-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_comments_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentAdmin',
        ),
    ]
