# Generated by Django 4.0.2 on 2022-05-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_delete_commentadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_added']},
        ),
    ]
