name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KET: some-test-key
      PYTHON_VERSION: 3.8
      MY_POSTGRES_USER: someuser
      MY_POSTGRES_PASSWORD: somepassword
      MY_POSTGRES_DB: github_actions
      MY_ENGINE: django.db.backends.postgresql
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.MY_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.MY_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.MY_POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: '0'
        DJANOG_SECRET_KEY: ${{ secrets.SECRET_KEY}}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_DATABASE: ${{ secrets.DB_NAME }}
        DB_ENGINE: ${{ secrets.DB_ENGINE }}
        DB_PORT: ${{ secrets.DB_PORT }}
      run: |
        python manage.py test
